### ISSUE TITLE
Improve search functionality

### ISSUE THREAD

**Issue by nocturnll** [tinyspeck/sleuth#78]
Currently, the search function uses regex. I'd like search to be much more intuitive, with better modifiers and fuzzier matching.

- Search modifiers (e.g. "term", -term)
- Slightly fuzzier matching (e.g. `term1 term2` should return matches that contain those terms in any order, rather than the literal)
- In-app documentation, either a tooltip by the search bar or in the top menus

**Comment by erickzhao** [comment]
I think the backbone of this implementation can be done using an open-source library like https://fusejs.io/
